### ISSUE TITLE
Basic questions

### ISSUE THREAD

**Issue by milesalex** [syzer/twitter-marketing-bot#6]
Noob here...

Trying to get the bot up and runnning and the first place I started was to see if the tests were running.

Getting Async errors
```sh
 FAIL  test/twitter/labelUser.test.js (11.572s)
  ✕ Can label user/AlainFrapolli to category1, which is important/programming (5023ms)
  ✕ Can find best label/product for the user/AlainFrapolli (5008ms)

  ● Can label user/AlainFrapolli to category1, which is important/programming

    Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.

      at node_modules/jest-jasmine2/build/queue_runner.js:68:21
      at Timeout.callback [as _onTimeout] (node_modules/jsdom/lib/jsdom/browser/Window.js:628:19)
```

After that I tried to drop console logs throughout the app to see where this are breaking/failing silently. What is the expected success message?

**Comment by syzer** [comment]
Sorry, must lost your this message..
@shortcircuit3 happy to help. Are you still interested?

**Comment by syzer** [comment]
You need access keys for twitter api
in .env file

CONSUMER_KEY=here
CONSUMER_SECRET=here
ACCESS_TOKEN=fill_out_here
ACCESS_TOKEN_SECRET=fill_out_here
